#!/bin/bash

# 系統管理：DNS 設定（高度可客製：預設供應商、套用方式）
# 注意：此檔案會被 source，請避免在此更改 shell options（例如 set -e）。

# 調整 DNS 位址
dns_apply_servers() {
    local dns1="${1:-}"
    local dns2="${2:-}"

    if [ -z "$dns1" ]; then
        tgdb_fail "DNS 位址不可為空" 1 || return $?
    fi

    if command -v systemctl >/dev/null 2>&1 && systemctl is-active systemd-resolved >/dev/null 2>&1; then
        echo "正在套用到 systemd-resolved..."
        sudo mkdir -p /etc/systemd
        sudo bash -c "cat > /etc/systemd/resolved.conf" <<EOF
[Resolve]
DNS=${dns1} ${dns2}
FallbackDNS=
EOF
        sudo systemctl restart systemd-resolved || true
        if [ -L /etc/resolv.conf ] || [ ! -e /etc/resolv.conf ]; then
            sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
        fi
        echo "✅ 已透過 systemd-resolved 設定 DNS。"
        return 0
    fi

    echo "systemd-resolved 未啟用，將直接寫入 /etc/resolv.conf（不加鎖）。"
    echo "# Generated by TGDB" | sudo tee /etc/resolv.conf > /dev/null
    echo "nameserver $dns1" | sudo tee -a /etc/resolv.conf > /dev/null
    if [ -n "$dns2" ]; then
        echo "nameserver $dns2" | sudo tee -a /etc/resolv.conf > /dev/null
    fi
    echo "✅ /etc/resolv.conf 已更新。部分系統可能仍由 NetworkManager/Netplan 管理。"
    return 0
}

manage_dns() {
    while true; do
        maybe_clear
        echo "=================================="
        echo "❖ 調整 DNS 位址 ❖"
        echo "=================================="
        if [ -f /etc/resolv.conf ]; then
            grep "^nameserver" /etc/resolv.conf || true
        else
            echo "文件 /etc/resolv.conf 不存在。"
        fi
        echo "----------------------------------"
        
        echo "請選擇 DNS 設定："
        echo "1. Cloudflare DNS (1.1.1.1, 1.0.0.1)"
        echo "2. Google DNS (8.8.8.8, 8.8.4.4)"
        echo "3. TGDB 預設 DNS (1.1.1.1, 8.8.8.8)"
        echo "4. 自訂 DNS（使用系統預設編輯器）"
        echo "5. 還原為系統自動管理（systemd-resolved/NetworkManager）"
        echo "----------------------------------"
        echo "0. 返回"
        echo "=================================="
        read -r -e -p "請輸入選擇 [0-5]: " dns_choice
        
        local dns1=""
        local dns2=""
        
        case $dns_choice in
            1)
                dns1="1.1.1.1"; dns2="1.0.0.1" ;;
            2)
                dns1="8.8.8.8"; dns2="8.8.4.4" ;;
            3)
                dns1="1.1.1.1"; dns2="8.8.8.8" ;;
            4)
                echo "即將使用系統預設編輯器編輯 /etc/resolv.conf..."
                pause
                local editor="${EDITOR:-}"
                if [ -z "$editor" ]; then
                    if command -v nano >/dev/null 2>&1; then
                        editor="nano"
                    elif command -v vi >/dev/null 2>&1; then
                        editor="vi"
                    else
                        editor="ed"
                    fi
                fi
                sudo "$editor" /etc/resolv.conf || true
                echo "✅ /etc/resolv.conf 已更新（未加鎖，交由系統管理）。"
                pause
                continue
                ;;
            5)
                echo ""
                if system_admin_confirm_yn "確定要還原為系統自動管理嗎？(Y/n，預設 Y，輸入 0 取消): " "Y"; then
                    if command -v systemctl >/dev/null 2>&1 && systemctl is-enabled systemd-resolved >/dev/null 2>&1; then
                        echo "正在還原 systemd-resolved 設定..."
                        if [ -f /etc/systemd/resolved.conf ]; then
                            sudo sed -i -E 's/^DNS=.*$/# DNS=/; s/^FallbackDNS=.*$/# FallbackDNS=/' /etc/systemd/resolved.conf
                        fi
                        sudo systemctl restart systemd-resolved || true
                        if [ -L /etc/resolv.conf ] || [ ! -e /etc/resolv.conf ]; then
                            sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
                        fi
                        echo "✅ 已還原為 systemd-resolved 管理。"
                    else
                        echo "未偵測到 systemd-resolved 啟用，僅移除手動固定設定（如有）。"
                    fi
                else
                    echo "操作已取消。"
                fi
                pause
                continue
                ;;
            0)
                return ;;
            *)
                echo "無效選項"; sleep 1; continue ;;
        esac

        dns_apply_servers "$dns1" "$dns2"
        pause
    done
}
