# 可選：站點獨立快取區（啟用時取消註解）
# proxy_cache_path /var/cache/nginx/<domain> keys_zone=cache_<domain_s>:10m levels=1:2 inactive=60m use_temp_path=off;

server {
    listen 80;
    server_name <fqdn>;
    return 301 https://<fqdn>$request_uri;
}

server {
    listen 443 ssl;                        # HTTP/2 由 http2 on; 啟用
    listen 443 quic reuseport;             # HTTP/3（QUIC）
    server_name <fqdn>;

    ssl_certificate     /etc/nginx/certs/<fqdn>.crt;
    ssl_certificate_key /etc/nginx/certs/<fqdn>.key;
    # HTTP/3 提示（Alt-Svc）
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        gzip off; # 僅靜態壓縮
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;      # WebSocket
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://<upstream_host_port>;
        # 可選：快取
        # proxy_cache cache_<domain_s>;
        # proxy_cache_valid 200 301 302 10m;
        # proxy_cache_bypass $http_cache_control $arg_nocache;
        client_max_body_size 1000m;  
    }
}